### DISCUSSION TITLE
Integrate inverter e.g. sungrow SH10RT

### DISCUSSION THREAD

**Discussion by HolBaum5** [ohAnd/EOS_connect#35] [Installation & Configuration] [answered]
Hello everyone, I have a sungrow inverter that I have already integrated under openHAB. How can I integrate it into the EOS_connect system? Do I have to make a new Intercae inverter_sungrow.py?

**Comment by HolBaum5** [comment]
Here briefly my procedure
1. Install **Modbus Binding** in openHAB,
2. Create **Modbus TCP Slave Bridge** thing from the Modbus Binding,
3. Generate **Sungrow Inverter** thing (in Modbus Binding) and items,
4. Integrate the topic **eos_connect/control/eos_discharge_allowed** into openHAB via MQTT and use it to control the inverter (I haven't done this yet),
5. Integrate **config.yaml** openHAB.
```
# Load configuration
load:
# Data source for load power - openhab, homeassistant, default
  source: openhab
# URL for openhab or homeassistant
  url: http://192.168.10.68:8080
# item / entity for load power data
  load_sensor: EosWallPower
# item / entity for wallbox power data
  car_charge_load_sensor: EosWallboxPower
# access token for homeassistant (optional)
  access_token: abc123
# EOS server configuration

Battery:
# Data source for battery soc - openhab, homeassistant, default
  source: openhab
# URL for openhab or homeassistant
  url: http://192.168.10.68:8080
# item / entity for battery SOC data
  soc_sensor: Sungrow_Inverter_Battery_Level_String
# access token for homeassistant (optional)
  access_token: abc123
# battery cpaacity in Wh
  capacity_wh: 11059
# efficiency for charging the battery
  charge_efficiency: 0.88
# efficiency for discharging the battery
  discharge_efficiency: 0.88
# max charging power in W
  max_charge_power_w: 5000
# URL for battery soc
  min_soc_percentage: 5
# URL for battery soc
  max_soc_percentage: 100

```
