### DISCUSSION TITLE
Electricity Price Configuration -> TOU Tarif like Octopus iOGo

### DISCUSSION THREAD

**Discussion by thecem** [ohAnd/EOS_connect#50] [Installation & Configuration]
https://github.com/ohAnd/EOS_connect/blob/main/src/CONFIG_README.md#electricity-price-configuration

Are TOU prices supported?

intelligent Octopus Go has the following prices:

0-5 Go Rate (eg 10cent)
5-24 Standard Rate (eg 25cent)

Is it possible to set prices in an array or list:

```
price:
  24h:  [0.10, 0.10, 0.10, 0.10, 0.10, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
```
Additional this should also be taken into account for Modul 3 (EnWG §14a) since the Grid-Fee is TOU based.

THX!

**Comment by ohAnd** [comment]
Currently not ... yet ;-)

Especially for Modul 3 it's interesting ...
So the question make it sense to seperate it... ? With the goal to have an easier understable config.

octopus energy could be treated in parallel to tibber, akkudoktor (stockprice), smartenergy_at - therefore the question: your mentioned tariff 'intelligent Octopus Go' is also provided per API (https://api.octopus.energy/v1/graphql)?
(I saw you were already deeper in this at your HA integration ;-) )

To go in the discussion:
1. tariffs will be selected by source vendor
2. grid provider things with a fixed configurable array for one day as shown from you...

Or...
Other question I got ... will be the "dynamic" grid transport prices maybe part of e.g. tibber or octopus or seperated? Currently on my side the one and only billing come from tibber incl. grid costs / taxes and so on...
So, will make it sense to separate it or have easily another "source" in this case local fixed configured array - same level as tibber and co?

**Comment by thecem** [comment]
Modul 3 Prices will not be implemented in the API Price for Tibber and Octopus, since there is no edi (MaKo) information that will adress this information. So the End User has to add or subtract the cost. Good example is evcc:


For fixed tariff there is no formula:
```
grid:
  # 3. octopus Intelligent Go IMSys & EnWG $14a Modul 3 (GP 17,75€/m)
  type: fixed
  price: 0.2827 # EUR/kWh (default / OIG-Standard)
  # NT: 1.99
  # ST: 6.64
  # HT: 12.75
  zones:
    - days: Mo-So
      hours: 0-5
      price: 0.1042 # EUR/kWh (IOG-Go-NT)
    - days: Mo-So
      hours: 5-6,11-15,23-0
      price: 0.2352 # EUR/kWh (IOG-ST & M3 NT)
    - days: Mo-So
      hours: 6-11,15-17,22-23
      price: 0.2817 # EUR/kWh (IOG-ST & M3 ST)
    - days: Mo-So
      hours: 17-22
      price: 0.3428 # EUR/kWh (IOG-ST & M3 HT)
```

for template tariff there could be a formula used grid:
```
tariffs:
  currency: DKK
  grid:
    type: energinet
    region: dk1
    charges: 0.81 
    tax: 0.25
    formula: |

      // setzte Standardgebühren (Winter)
      gridfee := 0.2929 // normale Zone
      if ts.Hour() < 6 {
        gridfee = 0.0976 // niedrige Zone
      } else if ts.Hour() >= 17 && ts.Hour() < 21 {
        gridfee = 0.8788 // hohe Zone
      }

      // Anpassung der Gebühren für Sommer (April - September)
      if ts.Month() >= 4 && ts.Month() <= 9 {
        gridfee = 0.1467 // normale Zone
        if ts.Hour() < 6 {
          gridfee = 0.0976 // niedrige Zone
        } else if ts.Hour() >= 17 && ts.Hour() < 21 {
          gridfee = 0.3808 // hohe Zone
        }
      }
      ( price + charges + gridfee ) * ( 1 + tax )
```
So if we could have a fixed tarif with "zones" or an 24h array this woud be the first step for dynamic or tou tariffs, e.g.:

```
source: fixed_24h_array
fixed_24h_array: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
token: tibberBearerToken
feed_in_price: 0.0755833
negative_price_switch: false
```
next step would be, if an array is listed to subtract the ST-Fee and ad the array fee to the price:

```
source: fixed_24h_array
fixed_24h_array: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
gridfee: [NT,NT,NT,NT,NT,ST,ST,ST,ST,ST,NT,NT,NT,NT,NT,ST,HT,HT,HT,HT,HT,HT,ST,NT]
gridfee_nt: 5
gridfee_st: 10 // the ST Price in M3 represents the Standard Grid Fee in every case
gridfee_ht: 25
token: tibberBearerToken
feed_in_price: 0.0755833
negative_price_switch: false
```
