### ISSUE TITLE
Fronius Firmware 1.36.5-1 start problems

### ISSUE THREAD

**Issue by danielaussieb** [ohAnd/EOS_connect#23]
Seit dem neuesten Firmwareupdate gibts folgenden fehler im log beim start

successfully started
2025-04-23 15:39:42 INFO [Main] Starting eos_connect - version: 0.1.9
2025-04-23 17:39:42 INFO [Main] set user defined time zone to Europe/Berlin and loglevel to DEBUG
2025-04-23 17:39:42 INFO [EOS] Getting EOS version: <2025-04-09
Traceback (most recent call last):
  File "/app/src/eos_connect.py", line 101, in <module>
    inverter_interface = FroniusWR(inverter_config)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/interfaces/inverter_fronius.py", line 78, in __init__
    self.previous_battery_config = self.get_battery_config()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/interfaces/inverter_fronius.py", line 166, in get_battery_config
    response = self.send_request(path, auth=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/interfaces/inverter_fronius.py", line 506, in send_request
    raise RuntimeError(
RuntimeError: [Inverter] Request 0 failed with 404-Not Found. 
	 path:/config/batteries, 
	params:None 
	headers {} 
	nonce 0 
	payload 
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2025-04-23 15:40:33 INFO [Main] Starting eos_connect - version: 0.1.9
2025-04-23 17:40:33 INFO [Main] set user defined time zone to Europe/Berlin and loglevel to DEBUG
2025-04-23 17:40:33 INFO [EOS] Getting EOS version: <2025-04-09
Traceback (most recent call last):
  File "/app/src/eos_connect.py", line 101, in <module>
    inverter_interface = FroniusWR(inverter_config)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/interfaces/inverter_fronius.py", line 78, in __init__
    self.previous_battery_config = self.get_battery_config()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/interfaces/inverter_fronius.py", line 166, in get_battery_config
    response = self.send_request(path, auth=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/interfaces/inverter_fronius.py", line 506, in send_request
    raise RuntimeError(
RuntimeError: [Inverter] Request 0 failed with 404-Not Found. 
	 path:/config/batteries, 
	params:None 
	headers {} 
	nonce 0 
	payload 
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by ohAnd** [comment]
Hi @danielaussieb ,

hab mal im hier gelinkten Branch einen "Quick Hack" anhand der Aussage in https://github.com/muexxl/batcontrol/issues/155 eingesetzt ohne Möglichkeit zu testen und demnach ebenso "vorzupreschen" ;-)

Gerne mal probieren, vielleicht war es 'nur' das ...

-------

Zum An/Abschalten unter Inverter in der config version mit dem u.g. String belegen.

```yaml
# Inverter configuration
inverter:
  type: fronius_gen24  # Type of inverter - fronius_gen24, default (default will disable inverter control - only displaying the target state) - preset: default
  address: 192.168.1.1 # Address of the inverter
  user: customer # Username for the inverter
  password: *********** # Password for the inverter
  max_grid_charge_rate: 5000 # Max grid charge rate in W - default: 5000
  max_pv_charge_rate: 5000 # Max PV charge rate in W - default: 5000
  max_bat_discharge_rate: 5000 # Max battery discharge rate in W (currently not used) - default: 5000
  version: ">=1.36.5-1" # Version of the inverter - default: "old" e.g. 1.35.8-1 and earlier
# EVCC configuration
```
