### ISSUE TITLE
Add other Loads (Heat pumps, Dishwasher, Washing machine)

### ISSUE THREAD

**Issue by PRiekenberg** [ohAnd/EOS_connect#34]
Hi, thank you for your nice work!

Is it possible to add other loads for the prediction like Heat pumps, dishwashers or washing machines?

It would be nice to have the next start date and time for the next dishwasher run or heat pump heat cycle. These values could be written back to home assistant via MQTT and then used in automations.

I think the EOS already supports these devices types.

**Comment by ohAnd** [comment]
I've played a little bit with that thing ...
And integrated for the first tries, the following:
- config has new part at load:
```yaml
additional_load_1_sensor: "additional_load_1_sensor", # item / entity for wallbox power data in watts. Leave empty if not used.
additional_load_1_runtime: 2 # runtime for additional load 1 in minutes - default: 0 (or empty) = not used
additional_load_1_consumption: 1500 # consumption for additional load 1 in Wh - default: 0 (or empty) = not used
```
- first param is useful to substract also this not regular load from the historic data to have a more accurate predicition, but not needed to give the following 2 params to EOS
- runtime and consumption is the need by EOS optimize request - means how long the homepliance should be running and which energy will bs consumed in that time (overall not per hour)

this will lead to 2 new mqtt outputs:
- EOS Home Appliance Released -> should the home appliance (dishwasher) start now yes/no given by optimisation result
- EOS Home Appliance Start Hour -> the optimized start hour in the next 48h - current hour of the day (until tomorrow end of day) given by optimisation result


_side note:
Currently, based on EOS web API, there is only one additional consumer possible. EOS itself seems has internally more possinbilites incl. specific starthour from when in the day the optimization should be taken the add load into account. So, here are currently some limits._

open:

Currently the optimization will take this info with every request - means it will be assumed that this "wish" is given for the next hours over whole day starting with every request again
-> so it has to be discussed
- in which "time frame" this request should be included - means specific start hour of the day and so the request will given here - or something like that ... 
- Additionally to that, let's assume that is a dishwasher with 3 h and 1500 Wh for that time - EOS will give back e.g. start at 3pm running until 6 and consuming 500Wh from 3-4, 500Wh from 4-5, ... -> Now it is 4 o'clock - EOS connect/ EOS should be know if the dishwasher was already started at 3 and giving only the remaining time and energy to EOS - to get the right feedback ...

Thus, the current implementation is aiming 'playing around with this' and not the final target. ;-)
