### ISSUE TITLE
The load sensor readout seems to be broken

### ISSUE THREAD

**Issue by paule96** [ohAnd/EOS_connect#46]
I currently try to use EOS connect in my home assistant installation.

I have configured the load settings as following:

```yaml
source: homeassistant
url: http://homeassistant.local:8123/
load_sensor: sensor.home_consumption_eos_connect
car_charge_load_sensor: sensor.home_consumption_eos_connect
access_token: eyJ.....
```

> Ignore the car charge load sensor because I just used it, to see if this fixes anything.

but when I wait for the optimization calculation I get the following result for the load:

![Image](https://github.com/user-attachments/assets/88a66bdb-2ae0-48c0-9fe4-646d5f132790)

So a predication of less then 10 watts.

The sensor in homeassistant looks like that:

![Image](https://github.com/user-attachments/assets/e4fa4199-78c3-42bb-81ed-cdcd41dca6dd)

So way higher than the prediction. And that always. (I actually tried here already with higher values because the sensor is currently my real consumption times 10)

I think something is off here.

> Note: What I also noted is, that optional parameters like the car_charge_load can not be removed.
