### ISSUE TITLE
Feed In Prices are not shown in Income

### ISSUE THREAD

**Issue by thecem** [ohAnd/EOS_connect#53]
EOS: https://github.com/Duetting/ha_eos_addon/tree/main/eos
EOS_Connect: latest develop 0.1.0.76-develop (0.1.0.77-develop not available for update right now)

I would expect the income shown by a multiply of feed_in_price, but the income is 0.
Ist there a configuration fault?

![Image](https://github.com/user-attachments/assets/4498cc4a-fc39-403c-9bc4-a457fabb188a)

<details>

<summary>HA Addon Config</summary>

``` yaml
load:
  source: homeassistant
  url: http://192.168.1.100:8123
  access_token: >-
    1234
  load_sensor: sensor.home_power
  car_charge_load_sensor: sensor.car_charge_load_sensor
  additional_load_1_sensor: sensor.additional_load_1
  additional_load_1_runtime: 3
  additional_load_1_consumption: 1500
eos:
  server: 192.168.1.100
  port: 8503
  timeout: 360
price:
  source: fixed_24h
  token: tibberBearerToken
  fixed_24h_array: >-
    15.07, 15.07, 15.07, 15.07, 15.07, 28.17, 28.17, 28.17, 28.17, 28.17, 28.17,
    28.17, 28.17, 28.17, 28.17, 28.17, 28.17, 28.17, 28.17, 28.17, 28.17, 28.17,
    28.17, 28.17
  feed_in_price: 0.0755833
  negative_price_switch: false
battery:
  source: homeassistant
  url: http://192.168.1.100:8123
  soc_sensor: sensor.state_of_charge_fronius_storage_0_http_fg2410ak3l_fritz_box
  access_token: >-
    1234
  capacity_wh: 28480
  charge_efficiency: 0.88
  discharge_efficiency: 0.88
  max_charge_power_w: 10000
  min_soc_percentage: 10
  max_soc_percentage: 100
  price_euro_per_wh_accu: 0.0001
pv_forecast:
  - name: balkon_dg
    lat: 50.0
    lon: 8.0
    azimuth: 52
    tilt: 60
    power: 900
    powerInverter: 1000
    inverterEfficiency: 0.9
    horizont: ""
  - name: balkon_og
    lat: 50.0
    lon: 8.0
    azimuth: 52
    tilt: 60
    power: 900
    powerInverter: 1000
    inverterEfficiency: 0.9
    horizont: ""
  - name: dach_nord_ost
    lat: 50.0
    lon: 8.0
    azimuth: -128
    tilt: 37
    power: 4620
    powerInverter: 4200
    inverterEfficiency: 0.9
    horizont: ""
  - name: dach_nord_west
    lat: 50.0
    lon: 8.0
    azimuth: 142
    tilt: 37
    power: 5390
    powerInverter: 4200
    inverterEfficiency: 0.9
    horizont: ""
  - name: dach_sud_ost
    lat: 50.0
    lon: 8.0
    azimuth: -38
    tilt: 37
    power: 5390
    powerInverter: 10000
    inverterEfficiency: 0.9
    horizont: ""
  - name: dach_sud_west
    lat: 50.0
    lon: 8.0
    azimuth: 52
    tilt: 36
    power: 1540
    powerInverter: 1500
    inverterEfficiency: 0.9
    horizont: ""
  - name: garage_dach
    lat: 50.0
    lon: 8.0
    azimuth: 52
    tilt: 35
    power: 1400
    powerInverter: 1200
    inverterEfficiency: 0.9
    horizont: ""
  - name: garten_wand
    lat: 50.0
    lon: 8.0
    azimuth: 52
    tilt: 21
    power: 350
    powerInverter: 300
    inverterEfficiency: 0.9
    horizont: ""
  - name: garten_haus
    lat: 50.0
    lon: 8.0
    azimuth: -24
    tilt: 21
    power: 1200
    powerInverter: 1200
    inverterEfficiency: 0.9
    horizont: ""
  - name: lounge_zaun
    lat: 50.0
    lon: 8.0
    azimuth: -24
    tilt: 90
    power: 1050
    powerInverter: 1050
    inverterEfficiency: 0.9
    horizont: ""
  - name: terrasse
    lat: 50.0
    lon: 8.0
    azimuth: 52
    tilt: 9
    power: 2800
    powerInverter: 2800
    inverterEfficiency: 0.9
    horizont: ""
  - name: wand
    lat: 50.0
    lon: 8.0
    azimuth: -38
    tilt: 90
    power: 7500
    powerInverter: 7500
    inverterEfficiency: 0.9
    horizont: ""
inverter:
  type: fronius_gen24
  address: 192.168.1.132
  user: customer
  password: xxxx
  max_grid_charge_rate: 9000
  max_pv_charge_rate: 10000
  max_bat_discharge_rate: 9000
evcc:
  url: http://192.168.1.100:7070
mqtt:
  enabled: true
  broker: localhost
  port: 1883
  user: mqtt
  password: xxxx
  tls: false
  ha_mqtt_auto_discovery: true
  ha_mqtt_auto_discovery_prefix: homeassistant
refresh_time: 6
time_zone: Europe/Berlin
eos_connect_web_port: 8081
log_level: debug

```

</details>
