### ISSUE TITLE
second load point from evcc

### ISSUE THREAD

**Issue by ohAnd** [ohAnd/EOS_connect#57]
> Yes, a second load point from evcc. 

 _Originally posted by @thecem in [#53](https://github.com/ohAnd/EOS_connect/issues/53#issuecomment-2950055829)_

**Comment by thecem** [comment]
Two cars. I think the details like now, a second time could be nice. I love it minimal, so even a combined info could be a solution. If you need additional parameters I could share.

**Comment by thecem** [comment]
Another info from evcc is at the moment not really addressable, since heat pumps/ etc. are not really a clean load and should be addressed by “additional load” since evcc is trying to squeezing load to a Wallbox profile, which is consequently for a charging controller, but even not for a EMS for HP or WM or a DW, TD. So for HP we have two main profiles an almost 24h load and a time based (hour) profile. And this is where EOS-Connect (EOS) kicks in.

**Comment by ohAnd** [comment]
maybe you can share from <evcc_ip>:7070/api/state the part of 

```json
"loadpoints": [
      {
        "chargePower": 0,
        "chargedEnergy": 0,
        "charging": false,
        "connected": false,
        "connectedDuration": 0,
        "mode": "pv",
        "smartCostActive": false,
        "vehicleName": "",
        "vehicleOdometer": 0,
        "vehicleRange": 0,
        "vehicleSoc": 0
....
      }
    ],
```
with the second loadpoint - and which data will be useful or not... or should be combined for showing...

**Comment by thecem** [comment]
```yaml
[
  {
    "batteryBoost": false,
    "chargeCurrents": [0, 0, 0],
    "chargeDuration": 7440,
    "chargePower": 0,
    "chargeRemainingDuration": 0,
    "chargeRemainingEnergy": 0,
    "chargeTotalImport": 9266.337,
    "chargeVoltages": [238, 237, 237],
    "chargedEnergy": 15661.51,
    "chargerFeatureHeating": false,
    "chargerFeatureIntegratedDevice": false,
    "chargerIcon": null,
    "chargerPhases1p3p": true,
    "chargerSinglePhase": false,
    "chargerStatusReason": "unknown",
    "charging": false,
    "connected": false,
    "connectedDuration": 38440,
    "disableDelay": 180,
    "disableThreshold": 0,
    "effectiveLimitSoc": 85,
    "effectiveMaxCurrent": 16,
    "effectiveMinCurrent": 6,
    "effectivePlanId": 0,
    "effectivePlanSoc": 0,
    "effectivePlanTime": null,
    "effectivePriority": 0,
    "enableDelay": 60,
    "enableThreshold": 0,
    "enabled": false,
    "limitEnergy": 0,
    "limitSoc": 0,
    "maxCurrent": 16,
    "minCurrent": 6,
    "mode": "pv",
    "offeredCurrent": 0,
    "phaseAction": "inactive",
    "phaseRemaining": 0,
    "phasesActive": 3,
    "phasesConfigured": 0,
    "planActive": false,
    "planEnergy": 0,
    "planOverrun": 0,
    "planPrecondition": 0,
    "planProjectedEnd": null,
    "planProjectedStart": null,
    "planTime": null,
    "priority": 0,
    "pvAction": "inactive",
    "pvRemaining": 0,
    "sessionCo2PerKWh": 3.728,
    "sessionEnergy": 15661.51,
    "sessionPrice": 1.249,
    "sessionPricePerKWh": 0.08,
    "sessionSolarPercentage": 97.906,
    "smartCostActive": false,
    "smartCostLimit": null,
    "smartCostNextStart": null,
    "title": "Hof",
    "vehicleClimaterActive": null,
    "vehicleDetectionActive": false,
    "vehicleIdentity": "",
    "vehicleLimitSoc": 0,
    "vehicleName": "500e",
    "vehicleOdometer": 34159,
    "vehicleRange": 0,
    "vehicleSoc": 0,
    "vehicleWelcomeActive": false
  },
  {
    "batteryBoost": false,
    "chargeCurrents": [0.022, 0.001, 0.001],
    "chargeDuration": 920,
    "chargePower": 0.803,
    "chargeRemainingDuration": 0,
    "chargeRemainingEnergy": 0,
    "chargeTotalImport": 1380.114,
    "chargeVoltages": [236.33, 238.43, 234.81],
    "chargedEnergy": 2630,
    "chargerFeatureHeating": false,
    "chargerFeatureIntegratedDevice": false,
    "chargerIcon": null,
    "chargerPhases1p3p": true,
    "chargerSinglePhase": false,
    "chargerStatusReason": "unknown",
    "charging": false,
    "connected": true,
    "connectedDuration": 0,
    "disableDelay": 180,
    "disableThreshold": 0,
    "effectiveLimitSoc": 93,
    "effectiveMaxCurrent": 16,
    "effectiveMinCurrent": 6,
    "effectivePlanId": 0,
    "effectivePlanSoc": 0,
    "effectivePlanTime": null,
    "effectivePriority": 0,
    "enableDelay": 60,
    "enableThreshold": 0,
    "enabled": false,
    "limitEnergy": 0,
    "limitSoc": 93,
    "maxCurrent": 16,
    "minCurrent": 6,
    "mode": "pv",
    "offeredCurrent": 0,
    "phaseAction": "inactive",
    "phaseRemaining": 0,
    "phasesActive": 3,
    "phasesConfigured": 0,
    "planActive": false,
    "planEnergy": 0,
    "planOverrun": 0,
    "planPrecondition": 0,
    "planProjectedEnd": null,
    "planProjectedStart": null,
    "planTime": null,
    "priority": 0,
    "pvAction": "inactive",
    "pvRemaining": 0,
    "sessionCo2PerKWh": 207.457,
    "sessionEnergy": 2630,
    "sessionPrice": 0.394,
    "sessionPricePerKWh": 0.15,
    "sessionSolarPercentage": 1.257,
    "smartCostActive": false,
    "smartCostLimit": null,
    "smartCostNextStart": null,
    "title": "Garage",
    "vehicleClimaterActive": false,
    "vehicleDetectionActive": false,
    "vehicleLimitSoc": 100,
    "vehicleName": "vwid4",
    "vehicleOdometer": 32287,
    "vehicleRange": 326,
    "vehicleSoc": 93,
    "vehicleWelcomeActive": false
  }
]

```
